# .bashrc

# Source global definitions
if [ -f /etc/bashrc ]; then
	. /etc/bashrc
fi

alias ts="DT=\`date +%Y-%m-%d-%H%M\`; echo \$DT"
alias ts-='export ts=$(mkdir -p ./-; mktemp -d `date +./-/%Y-%m-%d_XXX`); echo "\$ts: $ts"'
alias vv="vim -S ./1.vim"
alias rgrep='grep -iR'
alias http="http --pretty=format"
export TERM=xterm-256color
